blogger/config/routes.rb
Rails.application.routes.draw do

    resources :articles do
      resources :comments
    end
    resources :tags

    root to: 'articles#index'
end

blogger/app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :delete_all
	has_many :taggings
	has_many :tags, through: :taggings
	has_attached_file :image

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]



	def tag_list
		tags.join(", ")   # join will be using Tag.to_s
	end	

	def tag_list=(tags_string)
  		tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  		self.tags = new_or_found_tags
	end
end

blogger/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

blogger/app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings, dependent: :delete_all
	has_many :articles, through: :taggings

	def to_s
		name
	end


end

blogger/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper


  def index
    @articles = Article.all
  end

  def show 
  	@article = Article.find(params[:id])
    @comment =  Comment.new
    @comment.article_id = @article.id

  end

  def new
 	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)
  	@article.save
  	flash.notice =  "Article #{@article.title} has been added."
  	redirect_to article_path(@article)
  end

  def destroy
  	Article.find(params[:id]).destroy
  	flash.notice =  "Article #{params[:title]} has been deleted."
  	redirect_to articles_path
  end

  def update
  	@article = Article.find(params[:id])
  	@article.update(article_params)
  	flash.notice =  "Article #{@article.title} has been updated."
  	redirect_to articles_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

end

blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	include CommentsHelper
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save
    redirect_to article_path(@comment.article)
  end


end

blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find(params[:id])
	end
	
	def index
		@tags = Tag.all
	end
end

blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

blogger/app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end

end

blogger/app/helpers/comments_helper.rb
module CommentsHelper
  def comment_params
  	params.require(:comment).permit(:author_name, :body)
  end

end

blogger/app/helpers/tags_helper.rb
module TagsHelper
end

blogger/app/views/articles/_comment.html.erb
<p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
<h4>author : <%= comment.author_name %></h4>
<p class='comment'><%= comment.body %> </p>

blogger/app/views/articles/_form.html.erb
	<%= form_for (@article), html: {multipart: true } do |f| %>
		<ul> 
			<% @article.errors.full_messages.each do |error| %>
	    	<li><%= error %></li>
	  		<% end %>
		</ul>
		<p>
			<%= f.label :title %><br />
			<%= f.text_field :title %>
		</p>
		<p>
			<%= f.label :body %><br />
			<%= f.text_area :body %>
		</p>
		<p>
		<p>
			<%= f.label :tag_list%><br>
			<%= f.text_field :tag_list %>	
		</p>
		<p>
			<% if @article.image.exists? %>
				<%= image_tag @article.image.url %><br >
			<% end %>
			<%= f.label :image, "Attach an image" %><br />
			<%= f.file_field :image	%>
		</p>

			<%= f.submit %>
		</p>
	<% end %>

blogger/app/views/articles/edit.html.erb
<h1><%= %></h1>

<%= render partial: 'form' %>

blogger/app/views/articles/index.html.erb
<h1 class="bg"> All articles</h1>


<% @articles.each do |article| %>
	<ul id="articles">

	<li>
		<%= link_to article.title, article_path(article) %>
	</li>
	</ul>
<% end %>

<br><br>


<%= link_to "New article", new_article_path, class: "new_article" %> 
<%= link_to "Tags", tags_path %>

blogger/app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: "form" %>

blogger/app/views/articles/show.html.erb
<h1> <%= @article.title %></h1>

<!-- Yes, I know, this is pretty ugly for now, it's just very quickly done -->
<%= image_tag @article.image.url %>
<p class='article'>
	<%= @article.body %>
</p>
<br />

<p> Tags : <% @article.tags.each do |tag|%>
	<%=link_to tag.name , tag_path(tag) %>
<% end %>
</p>

<h3>Comments <%=  @article.comments.size %></h3>

<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>



<%= link_to "<< Back to Articles list", articles_path %> | <%= link_to "Edit", edit_article_path(@article) %> | 
<%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %>

blogger/app/views/comments/_form.html.erb
<h3> Post a comment </h3>
  <%= form_for [ @article , @comment]  do |f| %>
  <p>
    <%= f.label  :author_name, "Your name"%>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your comment" %>
    <%=f.text_area :body %></p>
  </p>
  <p>
    <%= f.submit "submit comment"  %>
  </p>
<% end %>

blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class='flash'><%= flash.notice %></p>
<%= yield %>

</body>
</html>

blogger/app/views/tags/index.html.erb
<h1> List of all tags on this blog</h1>
<ul><% @tags.each do |tag| %>
	<%= link_to tag.name, tag_path(tag) %> 
	<% end %>
</ul>

blogger/app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>